name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ['7.8', 'stable']
        racket-variant: ['regular']
        allow-failure: [false]
        include:
          - racket-version: 'current'
            racket-variant: 'CS'
            allow-failure: true
          - racket-version: 'current'
            racket-variant: 'regular'
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    name: Racket ${{ matrix.racket-version }} (${{ matrix.racket-variant }})
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
      - run: raco pkg install --auto
      - run: raco test .
